/* This file was autogenerated. */

#include "descriptors.h"
#include "../core/core.h"

void glsl_add_vulkan_global_uniform_buffer(UT_string *s, uint32_t set, uint32_t binding, uint32_t count) {
  utstring_printf(s, "layout(set = %u, binding = %u) uniform globalBlock {", set, binding);
 utstring_printf(s, "  mat4 viewMat;");
 utstring_printf(s, "  mat4 projMat;");
  utstring_printf(s, "} global");
  if (count == 1) {utstring_printf(s, ";\n");}
  else {utstring_printf(s, "[%u];\n", count);}
}
void glsl_add_vulkan_instances_uniform_buffer(UT_string *s, uint32_t set, uint32_t binding, uint32_t count) {
  utstring_printf(s, "layout(set = %u, binding = %u) uniform instancesBlock {", set, binding);
 utstring_printf(s, "  mat4 modelMat;");
  utstring_printf(s, "} instances");
  if (count == 1) {utstring_printf(s, ";\n");}
  else {utstring_printf(s, "[%u];\n", count);}
}
