/* This file was autogenerated. */

#include "descriptors.h"
#include "../core/core.h"

UT_string *vulkan_global_uniform_buffer_get_glsl_str(uint32_t set, uint32_t binding, uint32_t count) {
  UT_string *s;
  utstring_new(s);
  utstring_printf(s, "layout(set = %u, binding = %u) uniform globalBlock {", set, binding);
 utstring_printf(s, "  mat4 viewMat;");
 utstring_printf(s, "  mat4 projMat;");
  utstring_printf(s, "} global");
  if (count == 1) {utstring_printf(s, ";");}
  else {utstring_printf(s, "[%u];", count);}
  return s;
}
UT_string *vulkan_instance_data_uniform_buffer_get_glsl_str(uint32_t set, uint32_t binding, uint32_t count) {
  UT_string *s;
  utstring_new(s);
  utstring_printf(s, "layout(set = %u, binding = %u) uniform instance_dataBlock {", set, binding);
 utstring_printf(s, "  mat4 modelMat;");
  utstring_printf(s, "} instance_data");
  if (count == 1) {utstring_printf(s, ";");}
  else {utstring_printf(s, "[%u];", count);}
  return s;
}
