/* This file was autogenerated. */

#include "globals.h"
#include "../core/platform.h"
globals_ globals;
void globals_create() {
  globals.assetsFilePath = get_executable_dir_file_path("assets", "data.db");
  globals.configFilePath = get_executable_dir_file_path("assets", "config.ini");
}
void globals_destroy() {
  utstring_free(globals.assetsFilePath);
  utstring_free(globals.configFilePath);
}
