/* This file was autogenerated. */

#include "globals.h"
#include "../core/platform.h"
globals_ globals;
void globals_create() {
  globals.assetsDirname = get_executable_dir_file_path("", "assets");
  globals.assetDatabaseFilepath = get_executable_dir_file_path("", "assets/data.db");
  globals.assetConfigFilepath = get_executable_dir_file_path("", "assets/config.ini");
}
void globals_destroy() {
  utstring_free(globals.assetsDirname);
  utstring_free(globals.assetDatabaseFilepath);
  utstring_free(globals.assetConfigFilepath);
}
