/* This file was autogenerated. */

#pragma once
void globals_create();
void globals_destroy();
typedef struct globals_ {
  UT_string *assetsFilePath;
  UT_string *configFilePath;
} globals_;
extern globals_ globals;
