/* A packrat parser generated by PackCC 1.6.0 */

#ifndef PCC_INCLUDED__HOME_SSZCZYRB_REPOS_CPPTEST_SRC_PEG_C_PARSER_H
#define PCC_INCLUDED__HOME_SSZCZYRB_REPOS_CPPTEST_SRC_PEG_C_PARSER_H

#include "../c_parser_internal.h"
#ifdef __cplusplus
extern "C" {
#endif

typedef struct c_parser_context_tag c_parser_context_t;

c_parser_context_t *c_parser_create(c_parser_state *auxil);
int c_parser_parse(c_parser_context_t *ctx, c_parser_ast_node **ret);
void c_parser_destroy(c_parser_context_t *ctx);

#ifdef __cplusplus
}
#endif

#endif /* !PCC_INCLUDED__HOME_SSZCZYRB_REPOS_CPPTEST_SRC_PEG_C_PARSER_H */
