/* A packrat parser generated by PackCC 1.6.0 */

#ifndef PCC_INCLUDED__HOME_SSZCZYRB_REPOS_CPPTEST_SRC_PEG_GLSL_PARSER_H
#define PCC_INCLUDED__HOME_SSZCZYRB_REPOS_CPPTEST_SRC_PEG_GLSL_PARSER_H

#include "c_parser_internal.h"
c_parser_state glsl_parser_execute(char *source);
#ifdef __cplusplus
extern "C" {
#endif

typedef struct glsl_parser_context_tag glsl_parser_context_t;

glsl_parser_context_t *glsl_parser_create(c_parser_state *auxil);
int glsl_parser_parse(glsl_parser_context_t *ctx, c_parser_ast_node **ret);
void glsl_parser_destroy(glsl_parser_context_t *ctx);

#ifdef __cplusplus
}
#endif

#endif /* !PCC_INCLUDED__HOME_SSZCZYRB_REPOS_CPPTEST_SRC_PEG_GLSL_PARSER_H */
