/* This file was autogenerated. */

#include "camera.h"
#include "debug.h"
#include "device.h"
#include "functions.h"
#include "render_context.h"
#include "scene.h"
#include "scene_data.h"
#include "shader.h"
#include "swap_chain.h"
