/* This file was autogenerated. */

#include "data/camera.h"
#include "data/scene_data.h"
#include "debug.h"
#include "device.h"
#include "functions.h"
#include "geometry_buffer.h"
#include "render_context.h"
#include "scene.h"
#include "shader.h"
#include "swap_chain.h"
